[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
crowd_funding = "CRL1NdEMLm5ccWQGGHRMQMWPA2iN6Au51S37QeqmEVhB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/vibhushit/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
